version: "3"

services:
  image-previewer:
    container_name: image-previewer
    restart: always
    build:
      context: ../
      dockerfile: ./build/image_previewer.dockerfile
    ports:
      - "8080:80"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../tests/static:/static
      - ../tests/nginx.conf:/etc/nginx/conf.d/default.conf

  integration-tests:
    image: golang:1.16.2
    volumes:
      - ../:/app/
    working_dir: /app
    command: sh -c 'go test -v ./tests/... -tags=integration'
    depends_on:
      - nginx
      - image-previewer

networks:
  default:
    name: image_previewer_network