name: Otus project tests

on:
  push:
    branches:
      - main
      - 'features/**'

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.16

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48.0
          working-directory: ${{ env.BRANCH }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.16

      - name: Check out code
        uses: actions/checkout@v3

      - name: make build
        run: make build
        working-directory: ${{ env.BRANCH }}
        
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.16

      - name: Check out code
        uses: actions/checkout@v3

      - name: Unit tests
        run: go test -race -count 100 ./...
        working-directory: ${{ env.BRANCH }}
